#ifndef _KEYPAD_H_
#define _KEYPAD_H_

#include "stm32f4xx_hal.h"
#include "FreeRTOS.h"
#include "task.h"
#include "comunication.h"
#include "sensor.h"
#include "discoLeds.h"

#define DEBOUNCE_TIME 100
#define N_BUTTONS 13
#define DEBOUNCE_MAXIMUM 20

#define GMOTE_BUTTONS_IT_PRIORITY 6

#define GMOTE_BUTTON_0_PORT GPIOC
#define GMOTE_BUTTON_0_PIN GPIO_PIN_2
#define GMOTE_BUTTON_0_EXTI EXTI2_IRQn
extern const int GMOTE_BUTTON_0;

#define GMOTE_BUTTON_1_PORT GPIOC
#define GMOTE_BUTTON_1_PIN GPIO_PIN_3
#define GMOTE_BUTTON_1_EXTI EXTI3_IRQn
extern const int GMOTE_BUTTON_1;

#define GMOTE_BUTTON_2_PORT GPIOC
#define GMOTE_BUTTON_2_PIN GPIO_PIN_4
#define GMOTE_BUTTON_2_EXTI EXTI4_IRQn
extern const int GMOTE_BUTTON_2;

#define GMOTE_BUTTON_3_PORT GPIOC
#define GMOTE_BUTTON_3_PIN GPIO_PIN_5
#define GMOTE_BUTTON_3_EXTI EXTI9_5_IRQn
extern const int GMOTE_BUTTON_3;

#define GMOTE_BUTTON_4_PORT GPIOE
#define GMOTE_BUTTON_4_PIN GPIO_PIN_6
#define GMOTE_BUTTON_4_EXTI EXTI9_5_IRQn
extern const int GMOTE_BUTTON_4;

#define GMOTE_BUTTON_5_PORT GPIOE
#define GMOTE_BUTTON_5_PIN GPIO_PIN_7
#define GMOTE_BUTTON_5_EXTI EXTI9_5_IRQn
extern const int GMOTE_BUTTON_5;

#define GMOTE_BUTTON_6_PORT GPIOE
#define GMOTE_BUTTON_6_PIN GPIO_PIN_8
#define GMOTE_BUTTON_6_EXTI EXTI9_5_IRQn
extern const int GMOTE_BUTTON_6;

#define GMOTE_BUTTON_7_PORT GPIOE
#define GMOTE_BUTTON_7_PIN GPIO_PIN_9
#define GMOTE_BUTTON_7_EXTI EXTI9_5_IRQn
extern const int GMOTE_BUTTON_7;

#define GMOTE_BUTTON_8_PORT GPIOE
#define GMOTE_BUTTON_8_PIN GPIO_PIN_10
#define GMOTE_BUTTON_8_EXTI EXTI15_10_IRQn
extern const int GMOTE_BUTTON_8;

#define GMOTE_BUTTON_9_PORT GPIOE
#define GMOTE_BUTTON_9_PIN GPIO_PIN_11
#define GMOTE_BUTTON_9_EXTI EXTI15_10_IRQn
extern const int GMOTE_BUTTON_9;

#define GMOTE_BUTTON_10_PORT GPIOE
#define GMOTE_BUTTON_10_PIN GPIO_PIN_12
#define GMOTE_BUTTON_10_EXTI EXTI15_10_IRQn
extern const int GMOTE_BUTTON_10;

#define GMOTE_BUTTON_11_PORT GPIOE
#define GMOTE_BUTTON_11_PIN GPIO_PIN_13
#define GMOTE_BUTTON_11_EXTI EXTI15_10_IRQn
extern const int GMOTE_BUTTON_11;

#define GMOTE_BUTTON_12_PORT GPIOE
#define GMOTE_BUTTON_12_PIN GPIO_PIN_14
#define GMOTE_BUTTON_12_EXTI EXTI15_10_IRQn
extern const int GMOTE_BUTTON_12;

#define GMOTE_BUTTON_13_PORT GPIOE
#define GMOTE_BUTTON_13_PIN GPIO_PIN_15
#define GMOTE_BUTTON_13_EXTI EXTI15_10_IRQn
extern const int GMOTE_BUTTON_13;

void keypad_run(void *arg);

#endif
